### ISSUE TITLE
Possible to add DB_HOST as an optional setting in wp-cli.local.yml?

### ISSUE THREAD

**Issue by jtsternberg** [bigwing/local-wp-cli#2]
My DB host/port do not match what is hard-coded, (and what is in your screenshot), so I had to modify that constant. But that means the git repo is out of sync, and you already have other things in the yml file. Any reason not to add this?

My local DB settings:
![](http://b.ustin.co/mOPN38+)

**Comment by jtsternberg** [comment]
Oh, and awesome job with this! It's a great tool!

**Comment by jtsternberg** [comment]
Another thing... I was playing with this by moving the `wp-cli` directory to `~/Sites` instead of `~/Sites/project`. It works well, but again, the `DB_HOST` needs to be configurable from the per-project yml file.

Desired `~/Sites/project/wp-cli.local.yml`:
```
path: app/public
url: https://<projecturl>
user: jt
db_host: 192.168.75.100:4023
require:
  - ../wp-cli/local.php
  - ../wp-cli/quiet.php
apache_modules:
  - mod_rewrite
```

**Comment by jtsternberg** [comment]
DERP. I now realize this repo is pretty much nothing more than config via the small `wp-cli.local.yml` file and the small `local.php` and `quiet.php` files. No need to get all fancy as it's simple enough to copy those 3 (or just combine the 2 php files, making even less to copy around).

**Comment by jtsternberg** [comment]
I ended up creating a script for this: https://github.com/jtsternberg/Dot-Files/blob/master/bin/local-wpcli-config
It can be run remotely via https://github.com/jtsternberg/Dot-Files/blob/master/bin/local-wpcli-config#L14

**Comment by morganestes** [comment]
Yeah, as soon as you change a file it's out of sync, but I couldn't think of a way around that. I like your configurator script approach, as it's really only needed when the project is first set up. 👍
